#!/usr/bin/env bash
set -Eeuo pipefail

# Single-GPU runner for iSAID (MMDetection Mask R-CNN baseline).
#
# This script is meant to be a reproducible, one-command entrypoint.
# It:
# - optionally creates a dedicated venv
# - installs a pinned MMDet stack (torch+mmcv+mmdet)
# - picks a single GPU
# - prepares/checks the iSAID dataset layout
# - launches training via downstream/mmdet/train_isaid.sh
#
# NOTE:
# This repo previously referenced a non-existent script:
#   one_click_isaid_maskrcnn_a100_gpu0.sh
# We now directly call the maintained entrypoint:
#   downstream/mmdet/train_isaid.sh

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "[info] one_click_isaid_maskrcnn_a100_single.sh version=2025-12-28"

# Optional: create/use a dedicated venv for iSAID so package pins are reproducible.
# Override via:
#   export ISAID_VENV_DIR=/path/to/venv
#   export ISAID_SKIP_VENV=1        # use current python env as-is
#   export ISAID_SKIP_TORCH_INSTALL=1
#   export ISAID_TORCH_CUDA=cu118   # or cu121
ISAID_SKIP_VENV="${ISAID_SKIP_VENV:-0}"
ISAID_SKIP_TORCH_INSTALL="${ISAID_SKIP_TORCH_INSTALL:-0}"
ISAID_VENV_DIR="${ISAID_VENV_DIR:-${REPO_ROOT}/.venv_isaid_a100}"
ISAID_TORCH_CUDA="${ISAID_TORCH_CUDA:-cu118}"
ISAID_TORCH_VERSION="${ISAID_TORCH_VERSION:-2.1.0}"
ISAID_TORCHVISION_VERSION="${ISAID_TORCHVISION_VERSION:-0.16.0}"
# Always recreate the venv on each run to guarantee a clean environment.
ISAID_PYTHON="${ISAID_PYTHON:-python3}"
ISAID_CLEAN_WORK_DIR="${ISAID_CLEAN_WORK_DIR:-0}"

if [[ "${ISAID_SKIP_VENV}" != "1" ]]; then
  if [[ -d "${ISAID_VENV_DIR}" ]]; then
    echo "[info] Removing existing venv (forced recreate): ${ISAID_VENV_DIR}"
    rm -rf "${ISAID_VENV_DIR}"
  fi

  echo "[info] Creating venv: ${ISAID_VENV_DIR}"
  "${ISAID_PYTHON}" -m venv "${ISAID_VENV_DIR}"

  # shellcheck disable=SC1090
  source "${ISAID_VENV_DIR}/bin/activate"
  PY_BIN="$(command -v python)"
  export PY_BIN
  python -m pip install -U pip setuptools wheel

  if [[ "${ISAID_SKIP_TORCH_INSTALL}" != "1" ]]; then
    echo "[info] Ensuring CUDA PyTorch (${ISAID_TORCH_CUDA}) torch==${ISAID_TORCH_VERSION} torchvision==${ISAID_TORCHVISION_VERSION}"
    if [[ "${ISAID_TORCH_CUDA}" == "cu121" ]]; then
      python -m pip install -U "numpy==1.26.4" "torch==${ISAID_TORCH_VERSION}+cu121" "torchvision==${ISAID_TORCHVISION_VERSION}+cu121" --index-url https://download.pytorch.org/whl/cu121
    else
      python -m pip install -U "numpy==1.26.4" "torch==${ISAID_TORCH_VERSION}+cu118" "torchvision==${ISAID_TORCHVISION_VERSION}+cu118" --index-url https://download.pytorch.org/whl/cu118
    fi

    python - <<'PY'
import torch
import numpy as np
print("[info] torch:", torch.__version__)
print("[info] numpy:", np.__version__)
print("[info] torch.version.cuda:", torch.version.cuda)
print("[info] torch.cuda.is_available:", torch.cuda.is_available())
PY
  fi

  # Install the pinned MMDet stack.
  python -m pip install -U -r "${REPO_ROOT}/requirements-isaid.txt"
fi

# ---------------------------
# Runtime knobs
# ---------------------------

# Pick a single GPU.
ISAID_GPU_ID="${ISAID_GPU_ID:-3}"
ISAID_RESPECT_CUDA_VISIBLE_DEVICES="${ISAID_RESPECT_CUDA_VISIBLE_DEVICES:-0}"

if [[ "${ISAID_RESPECT_CUDA_VISIBLE_DEVICES}" == "1" ]] && [[ -n "${CUDA_VISIBLE_DEVICES:-}" ]]; then
  echo "[info] Respecting existing CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
else
  export CUDA_VISIBLE_DEVICES="${ISAID_GPU_ID}"
fi

# Dataset root and work dir.
export ISAID_ROOT="${ISAID_ROOT:-${REPO_ROOT}/datasets}"
export WORK_DIR="${WORK_DIR:-${REPO_ROOT}/work_dirs/isaid_maskrcnn_gpu${CUDA_VISIBLE_DEVICES}}"

if [[ "${ISAID_CLEAN_WORK_DIR}" == "1" ]] && [[ -d "${WORK_DIR}" ]]; then
  echo "[info] Removing existing WORK_DIR (ISAID_CLEAN_WORK_DIR=1): ${WORK_DIR}"
  rm -rf "${WORK_DIR}"
fi

# Performance-oriented defaults (all user-overridable).
# Your logs show data_time ~= time, which means the GPU is waiting on the dataloader.
# These defaults aim to reduce data_time for iSAID's many PNG files.
export ISAID_NUM_WORKERS="${ISAID_NUM_WORKERS:-8}"
export ISAID_PERSISTENT_WORKERS="${ISAID_PERSISTENT_WORKERS:-1}"
export ISAID_PIN_MEMORY="${ISAID_PIN_MEMORY:-1}"
# PyTorch DataLoader prefetch_factor (only applies when num_workers > 0)
export ISAID_PREFETCH_FACTOR="${ISAID_PREFETCH_FACTOR:-4}"

# Speed vs memory tradeoff: gradient checkpointing in ResNet backbone.
# - 0 (default): faster
# - 1: lower memory, slower
export ISAID_WITH_CP="${ISAID_WITH_CP:-0}"

# Optional: reduce CPU resize load if you are bottlenecked (override as needed).
# Format: "W,H"
export ISAID_RESIZE="${ISAID_RESIZE:-1024,640}"
export ISAID_TEST_RESIZE="${ISAID_TEST_RESIZE:-1024,640}"

mkdir -p "${WORK_DIR}"
cat >"${WORK_DIR}/run_env.txt" <<EOF
# Generated by one_click_isaid_maskrcnn_a100_single.sh
CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
ISAID_ROOT=${ISAID_ROOT}
WORK_DIR=${WORK_DIR}
ISAID_NUM_WORKERS=${ISAID_NUM_WORKERS}
ISAID_PERSISTENT_WORKERS=${ISAID_PERSISTENT_WORKERS}
ISAID_PIN_MEMORY=${ISAID_PIN_MEMORY}
ISAID_PREFETCH_FACTOR=${ISAID_PREFETCH_FACTOR}
ISAID_WITH_CP=${ISAID_WITH_CP}
ISAID_RESIZE=${ISAID_RESIZE}
ISAID_TEST_RESIZE=${ISAID_TEST_RESIZE}
ISAID_BATCH_SIZE=${ISAID_BATCH_SIZE:-<default_in_config>}
ISAID_ACCUM=${ISAID_ACCUM:-${ISAID_GRAD_ACCUM:-<default_in_config>}}
ISAID_AMP=${ISAID_AMP:-<default_in_config>}
EOF

echo "[info] ISAID_ROOT=${ISAID_ROOT}"
echo "[info] WORK_DIR=${WORK_DIR}"
echo "[info] CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"
echo "[info] ISAID_NUM_WORKERS=${ISAID_NUM_WORKERS} ISAID_PERSISTENT_WORKERS=${ISAID_PERSISTENT_WORKERS} ISAID_PIN_MEMORY=${ISAID_PIN_MEMORY} ISAID_PREFETCH_FACTOR=${ISAID_PREFETCH_FACTOR}"
echo "[info] ISAID_WITH_CP=${ISAID_WITH_CP}"
echo "[info] ISAID_RESIZE=${ISAID_RESIZE}"

# Launch the maintained training entrypoint.
exec bash "${REPO_ROOT}/downstream/mmdet/train_isaid.sh"
