#!/usr/bin/env bash
set -Eeuo pipefail

# Train iSAID instance segmentation with MMDetection (Mask R-CNN baseline).
#
# Prereq: install mmdet + mmcv (recommended via openmim) in the current environment.
#
# Usage:
#   export ISAID_ROOT=/data/iSAID          # optional (default: repo_root/datasets)
#   export CUDA_VISIBLE_DEVICES=0          # optional (default: 0)
#   bash downstream/mmdet/train_isaid.sh
#
# Optional:
#   export ISAID_BATCH_SIZE=2
#   export ISAID_NUM_WORKERS=4
#   export ISAID_PERSISTENT_WORKERS=1
#   export ISAID_PIN_MEMORY=1
#   export ISAID_RESIZE=1024,640
#   export WORK_DIR=work_dirs/isaid_maskrcnn
#   export ISAID_LOAD_FROM=/path/to/pretrained.pth
#   export ISAID_EXTRACT_ZIPS=1            # try to extract Pxxxx.png from any *.zip under train/ and val/

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ISAID_ROOT="${ISAID_ROOT:-${REPO_ROOT}/datasets}"
export ISAID_ROOT
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PYTHONFAULTHANDLER="${PYTHONFAULTHANDLER:-1}"
export TORCH_SHOW_CPP_STACKTRACES="${TORCH_SHOW_CPP_STACKTRACES:-1}"

if [[ ! -d "${ISAID_ROOT}" ]]; then
  echo "[fail] ISAID_ROOT is not a directory: ${ISAID_ROOT}"
  exit 2
fi

WORK_DIR="${WORK_DIR:-work_dirs/isaid_maskrcnn}"
CONFIG="downstream/mmdet/isaid_mask_rcnn_r50_fpn_1x.py"

echo "[info] ISAID_ROOT=${ISAID_ROOT}"
echo "[info] WORK_DIR=${WORK_DIR}"
echo "[info] CONFIG=${CONFIG}"
echo "[info] CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}"

# Helpful perf knobs (read by downstream/mmdet/isaid_mask_rcnn_r50_fpn_1x.py)
echo "[info] ISAID_BATCH_SIZE=${ISAID_BATCH_SIZE:-<default_in_config>} ISAID_ACCUM=${ISAID_ACCUM:-${ISAID_GRAD_ACCUM:-<default_in_config>}} ISAID_AMP=${ISAID_AMP:-<default_in_config>}"
echo "[info] ISAID_NUM_WORKERS=${ISAID_NUM_WORKERS:-<default_in_config>} ISAID_PERSISTENT_WORKERS=${ISAID_PERSISTENT_WORKERS:-<default_in_config>} ISAID_PIN_MEMORY=${ISAID_PIN_MEMORY:-<default_in_config>}"
echo "[info] ISAID_RESIZE=${ISAID_RESIZE:-<default_in_config>} ISAID_TEST_RESIZE=${ISAID_TEST_RESIZE:-<default_in_config>}"

mkdir -p "${WORK_DIR}"
cat >"${WORK_DIR}/run_env_train_isaid.txt" <<EOF
# Generated by downstream/mmdet/train_isaid.sh
DATE_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || echo unknown)
REPO_ROOT=${REPO_ROOT}
ISAID_ROOT=${ISAID_ROOT}
WORK_DIR=${WORK_DIR}
CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}

ISAID_BATCH_SIZE=${ISAID_BATCH_SIZE:-}
ISAID_ACCUM=${ISAID_ACCUM:-}
ISAID_GRAD_ACCUM=${ISAID_GRAD_ACCUM:-}
ISAID_AMP=${ISAID_AMP:-}
ISAID_NUM_WORKERS=${ISAID_NUM_WORKERS:-}
ISAID_PERSISTENT_WORKERS=${ISAID_PERSISTENT_WORKERS:-}
ISAID_PIN_MEMORY=${ISAID_PIN_MEMORY:-}
ISAID_RESIZE=${ISAID_RESIZE:-}
ISAID_TEST_RESIZE=${ISAID_TEST_RESIZE:-}
ISAID_LOAD_FROM=${ISAID_LOAD_FROM:-}
EOF

EXTRACT_ARGS=()
if [[ "${ISAID_EXTRACT_ZIPS:-0}" == "1" ]]; then
  EXTRACT_ARGS+=(--extract)
fi
ANN_ARGS=()
if [[ -n "${ISAID_TRAIN_ANN:-}" ]]; then
  ANN_ARGS+=(--train_ann "${ISAID_TRAIN_ANN}")
fi
if [[ -n "${ISAID_VAL_ANN:-}" ]]; then
  ANN_ARGS+=(--val_ann "${ISAID_VAL_ANN}")
fi
PY_BIN="${PY_BIN:-python3}"
if ! command -v "${PY_BIN}" >/dev/null 2>&1; then
  PY_BIN="python"
fi
"${PY_BIN}" -c "import mim" >/dev/null 2>&1 || {
  echo "[fail] openmim not found in this environment. Install it first: ${PY_BIN} -m pip install -U openmim"
  exit 2
}
"${PY_BIN}" "${REPO_ROOT}/downstream/mmdet/prepare_isaid.py" --isaid_root "${ISAID_ROOT}" "${EXTRACT_ARGS[@]}" "${ANN_ARGS[@]}"

"${PY_BIN}" -m mim train mmdet "${CONFIG}" --work-dir "${WORK_DIR}"
